# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

test_simple_job:
  script:
    - echo I should execute for any pipeline trigger.


# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  HOME_DIR: "$CI_PROJECT_DIR/"
  PIP_REQUIREMENTS: "$CI_PROJECT_DIR/requirements.txt"


stages:
  - analysis
  - test
  - dist
  - publish

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.

cache:
  key: one-key-to-rule-them-all
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - mkdir -p .cache/pip
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate


test:
  script:
    - cd $HOME_DIR
    - pip install -r $PIP_REQUIREMENTS
    - python -m nose -v --nocapture test.test_simple

